// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWxMHCzHVIKD8klJVLHeSAy9vnr1KU1CE',
    appId: '1:453781229114:web:420667a68c1561a96caf03',
    messagingSenderId: '453781229114',
    projectId: 'online-store-a',
    authDomain: 'online-store-a.firebaseapp.com',
    storageBucket: 'online-store-a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_sjFOK0ewZJdfkdd2XezT0r1ZGc3m4O0',
    appId: '1:453781229114:android:96349ae00f05a0516caf03',
    messagingSenderId: '453781229114',
    projectId: 'online-store-a',
    storageBucket: 'online-store-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFP6zeD0NfUsBjo1TldKYgXrgH7oELpz0',
    appId: '1:453781229114:ios:6e616c3da0dbdfe56caf03',
    messagingSenderId: '453781229114',
    projectId: 'online-store-a',
    storageBucket: 'online-store-a.appspot.com',
    iosClientId: '453781229114-kspm6f1pvej7cjp3chkk539r7dhfqs57.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFP6zeD0NfUsBjo1TldKYgXrgH7oELpz0',
    appId: '1:453781229114:ios:6e616c3da0dbdfe56caf03',
    messagingSenderId: '453781229114',
    projectId: 'online-store-a',
    storageBucket: 'online-store-a.appspot.com',
    iosClientId: '453781229114-kspm6f1pvej7cjp3chkk539r7dhfqs57.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );
}
